{
 "title": "GPU Cluster Overview",
 "tags": [
  "gpu",
  "custom"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(hostname)" } },
   { "name": "username", "query": { "query": "label_values(username)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(hostname) (gpu_utilization_Percentage))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "x": 4, "y": 1, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gpu_utilization_Percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg GPU Utilization",
   "type": "stat",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_utilization_Percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg VRAM Used",
   "type": "stat",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_memory_percent_Percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Status", "type": "row", "gridPos": { "x": 0, "y": 5, "w": 24, "h": 1 } },
  {
   "title": "GPU Status by Server",
   "type": "table",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 10 },
   "targets": [
    { "expr": "gpu_utilization_Percentage", "legendFormat": "__auto" },
    { "expr": "gpu_memory_percent_Percentage", "legendFormat": "__auto" },
    { "expr": "gpu_temperature_C", "legendFormat": "__auto" },
    { "expr": "gpu_power_usage_W", "legendFormat": "__auto" }
   ]
  },
  { "title": "Process -> Container", "type": "row", "gridPos": { "x": 0, "y": 17, "w": 24, "h": 1 } },
  {
   "title": "GPU Processes",
   "type": "table",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 13 },
   "targets": [
    {
     "expr": "process_cpu_percent_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_rss_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_sm_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_encoder_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_decoder_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_running_time_Second{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_info_info{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "host_virtual_memory_total_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_memory_total_MiB{hostname!~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_process_container_info{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}