#!/usr/bin/env bash
# Writes nvidia-devices.override.yml: an extra compose file that lists this
# host's NVIDIA device nodes explicitly for the monitoring containers.
#
# Why: with Docker's systemd cgroup driver, GPU access that comes only from
# `gpus: all` is lost whenever systemd reloads (`systemctl daemon-reload`, an
# unattended-upgrades run, ...). The containers keep running, but every new
# NVML call inside them fails with "Failed to initialize NVML: Unknown
# Error", so GPU stats and GPU-process attribution silently stop. Devices
# listed explicitly under `devices:` are part of the container's own cgroup
# config and survive the reload. See README "Failed to initialize NVML".
#
# Usage (run on the GPU node, in this directory):
#   ./gen-nvidia-devices.sh                       # all three services (monitored-node-compose.yml)
#   ./gen-nvidia-devices.sh nvitop-exporter gpu-process-exporter   # exporter-compose.yml
# then add the file to every compose command for that node:
#   docker compose --env-file .env.node -f monitored-node-compose.yml \
#     -f nvidia-devices.override.yml up -d
set -euo pipefail

out="nvidia-devices.override.yml"
services=("$@")
[ ${#services[@]} -gt 0 ] || services=(beszel-agent nvitop-exporter gpu-process-exporter)

# char devices only (skips the /dev/nvidia-caps directory)
devices=()
for dev in /dev/nvidia[0-9]* /dev/nvidiactl /dev/nvidia-uvm /dev/nvidia-uvm-tools /dev/nvidia-modeset; do
  [ -c "$dev" ] && devices+=("$dev")
done
[ ${#devices[@]} -gt 0 ] || { echo "no /dev/nvidia* devices found on this host" >&2; exit 1; }

{
  echo "# Generated by gen-nvidia-devices.sh for $(hostname) -- host specific, do not commit."
  echo "services:"
  for svc in "${services[@]}"; do
    echo "  $svc:"
    echo "    devices:"
    for dev in "${devices[@]}"; do echo "      - $dev:$dev"; done
  done
} > "$out"

echo "wrote $out:"
cat "$out"
